config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'

  get 'products/raw' => 'products#raw'
  get 'products/all' => 'products#all'
  get 'products/list' => 'products#list'
  get 'products/pre_view' => 'products#pre_view'
  get 'products/:id/pre_view' => 'products#pre_view'
  get 'tag/:id/destroy' => 'tags#destroy', as: :tag_destroy

  post 'products/imagecrop' => 'products#imagecrop'
  post 'regrams/tag' => 'regrams#tag'
  post 'rocket_regrams/tag' => 'rocket_regrams#tag'

  resources :homes
  resources :products, shallow: true do
    member do
      get 'empty'
    end
  end
  resources :members
  resources :regrams
  resources :tags
  resources :counts
  resources :rockets, shallow: true do
    resources :mission_checks do
      collection do
        post 'change'
      end
    end
    resources :missions
    resources :rocket_regrams do
      collection do
        get 'list'
      end
    end
    member do
      get 'calendar'
      get 'attend'
      get 'attend_show'
      get 'absent'
      get 'mission'
      post 'check'
      post 'upload_csv'
      post 'reset_apply'
    end
  end
  resources :rocket_members
  resources :rocket_apply do
    member do
      get 'excel'
      post 'pass'
    end
  end
  resources :facebooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/regram.rb
class Regram < ApplicationRecord
  belongs_to :member

  belongs_to :timepool

  has_many :pics, dependent: :destroy
  accepts_nested_attributes_for :pics, allow_destroy: true
end

app/controllers/regrams_controller.rb
class RegramsController < ApplicationController
  def index
    @regrams = Regram.all
    @today = Date.today
    @dayofweek = @today.wday
    @timepool = Timepool.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @regramss }
    end
  end

  def new
    @regram = Regram.new
    @regram.pics.build

    # Date & Time
    now_date = Date.today.in_time_zone("Seoul").to_s
    now_time = Time.now.in_time_zone("Seoul").strftime("%H")
    times = Timepool.all.pluck(:time)

    for i in 0..(times.count - 1) do
      if now_time.to_i < times[i].to_i
        time_id = Timepool.where(time: times[i]).take.id
        time_index = i
        break
      end
    end

    if Regram.where(date: now_date).where(timepool_id: time_id).present?
      for i in (time_index + 1)..(Timepool.all.count - 1) do
        unless Regram.where(date: now_date).where(timepool_id: Timepool.where(time: times[i]).take.id).present?
          date = now_date
          time = Timepool.where(time: times[i]).take.id
          break
        end
      end

      if date.nil? || time.nil?
        for i in 0..100 do
          for j in 0..(Timepool.count - 1) do
            if Regram.where(date: (Date.today + i + 1).to_s).where(timepool_id: Timepool.where(time: times[j]).take.id).take.nil?
              date = (Date.today + i + 1).to_s
              time = Timepool.where(time: times[j]).take.id
              break
            end
          end
        end
      end
    else
      date = now_date
      time = time_id
    end

    params[:id].nil? ? @member = nil : @member = Member.find(params[:id])
    params[:date].nil? ? @date = date.to_date : @date = params[:date]
    params[:time].nil? ? @time = time : @time = Timepool.where(time: params[:time]).take.id

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @regram }
    end
  end

  def create
    @regram = Regram.new(regram_params)
    @regram.member_id = Member.where(email: params[:regram][:member_id]).take.id

    respond_to do |format|
      if @regram.save
        flash[:notice] = 'Regram was successfully created.'
        format.html { redirect_to(edit_regram_path(@regram)) }
        format.xml  { render xml: @regram, status: :created, location: @regram }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @regram.errors, status: :unprocessable_entity }
        p @regram.errors.full_messages
      end
    end
  end

  def edit
    @regram = Regram.find(params[:id])
    @member = Member.find(@regram.member_id)
    @date = @regram.date
    @time = @regram.timepool_id
  end

  def update
    @regram = Regram.find(params[:id])
    rp = regram_params.merge(member_id: Member.where(email: params[:regram][:member_id]).take.id)

    respond_to do |format|
      if @regram.update(rp)
        flash[:notice] = 'Regram was successfully updated.'
        format.html { redirect_to(edit_regram_path(@regram)) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @regram.errors, status: :unprocessable_entity }
        puts @regram.errors.full_messages
      end
    end
  end

  def destroy
    @regram = Regram.find(params[:id])
    @regram.destroy

    respond_to do |format|
      format.html { redirect_to(regrams_url) }
      format.xml  { head :ok }
    end
  end

  def tag
    type = params[:type]
    val = params[:val]

    if params[:val].present?
      if type == "user-tag"
        render json: { text: "\n-\nfrom @#{val}" }
      else
        render json: { text: "\n-\n#{Tag.find(val).content}" }
      end
    else
      render json: { text: "\n-\nfrom @#{params[:val1]}\n-\n#{Tag.find(params[:val2]).content}\n-\n#{Tag.find(params[:val3]).content}" }
    end
  end

  private

  def regram_params
    params.require(:regram).permit(:date, :url, :content, :member_id, :product_id, :timepool_id,
                                   pics_attributes: [:user_name, :id, :img, :img_cache, :_destroy])
  end
end

app/helpers/regrams_helper.rb
module RegramsHelper
end

app/views/regrams/_form.html.erb
<%= f.label :date, "일정" %>
<%= f.date_field :date, value: date.nil? ? "" : date, class: "form-control" %>
<%= f.label :timepool_id, "시간" %>
<%= f.select :timepool_id, options_from_collection_for_select(Timepool.all, :id, :time, regram.timepool_id.nil? ? (time.nil? ? "" : time) : regram.timepool_id), {}, {class: 'form-control select-time'} %>
<%= f.label :member_id, "ID" %>
<%= f.text_field :member_id, value: member.nil? ? "" : member.email, class: "form-control" %>
<%= f.label :product_id, "관심제품" %>
<%= f.select :product_id, options_from_collection_for_select(Product.all, :id, :name), {}, class: "form-control" %>
<%= f.label :content, "내용", class: "label-top" %>
<%= f.text_area :content, class: "form-control" %>
<div class="content-btn">
  <%= text_field_tag :user_tag, member.nil? ? "" : member.email, class: "form-control" %>
  <span id="user-tag" class="btn btn-success btn-tag">사용자 태그 삽입</span>
  <%= select_tag :product_tag, options_from_collection_for_select(Tag.where(category: 1).all, :id, :title, Tag.where(category: 1).last), class: "form-control" %>
  <span id="product-tag" class="btn btn-success btn-tag">제품 태그 삽입</span>
  <%= select_tag :instagram_tag, options_from_collection_for_select(Tag.where(category: 2).all, :id, :title, Tag.where(category: 2).last), class: "form-control" %>
  <span id="instagram-tag" class="btn btn-success btn-tag">인스타그램 태그 삽입</span>
  <span id="all-tag" class="btn btn-primary btn-tag">모든 태그 삽입</span>
</div>
<%= f.label :img, "이미지", class: "label-top" %>
<div class="input-image">
  <%= f.fields_for :pics do |p| %>
    <div>
      <%= p.file_field :img, class: "input-file-field form-control", data: {index_no: p.index} %>
      <%= p.hidden_field :img_cache %>
      <%= p.hidden_field :user_name, value: member.nil? ? "" : member.email, id: "user_name" %>
      <%= p.label :img, class: "img_label" do %>
        <%= image_tag p.object.img.present? ? p.object.img.url : asset_path("link.svg"), class: "preview", id: "preview#{p.index}" %>
      <% end %>
      <% if params[:action] == "edit" && p.object.img.present? %>
        <a download href="<%= p.object.img.url %>" class="btn btn-default">다운로드</a>
      <% end %>
      <%= p.link_to_remove '취소', class: 'btn pics_delete_btn remove_pics' %>
    </div>
  <% end %>
  <%= f.link_to_add "", :pics, id: 'pics', class: 'pics_add_btn' %>
</div>
<%= f.label :url, "URL" %>
<%= f.text_field :url, class: "form-control" %>

app/views/regrams/_nav.html.erb
<%= link_to root_path do %>
  <h2 class="main-title">motemote</h2>
<% end %>

<div class="nav">
  <%= link_to "스케줄", regrams_path, class: "main-link #{params[:controller] == "regrams" && "active"}" %>
  <%= link_to "회원정보", members_path, class: "main-link #{params[:controller] == "members" && "active"}" %>
  <%= link_to "태그관리", tags_path, class: "main-link #{params[:controller] == "tags" && "active"}" %>
  <%= link_to "페이스북", facebooks_path, class: "main-link #{params[:controller] == "facebook" && "active"}" %>
</div>

app/views/regrams/_nav_sub.html.erb
<div class="sub-nav">
  <% if params[:controller] == "regrams" && params[:action] != "index" %>
    <%= link_to "리그램등록", new_regram_path, class: "main-link #{params[:action] == "new" && "active"}" %>
  <% end %>
  <% if params[:controller] == "members" && params[:action] != "index" %>
    <%= link_to "회원등록", new_member_path, class: "main-link #{params[:action] == "new" && "active"}" %>
  <% end %>
  <% if params[:controller] == "tags" && params[:action] != "index" %>
    <%= link_to "태그등록", new_tag_path, class: "main-link #{params[:action] == "new" && "active"}" %>
  <% end %>
  <% if params[:controller] == "tags" && params[:action] != "index" %>
    <%= link_to "이미지 등록", new_facebook_path, class: "main-link #{params[:action] == "new" && "active"}" %>
  <% end %>
</div>

app/views/regrams/edit.html.erb
<%= render partial: 'nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <%= nested_form_for @regram, html: { class: "form-group form-regram", multipart: true } do |f| %>
      <%= render partial: 'form', locals: { f: f, regram: @regram, member: @member, date: @date, time: @time } %>
      <div class="btn-wrapper">
        <span class="btn btn-default btn-copy">글 복사</span>
        <%= f.submit "수정", class: "btn btn-primary" %>
        <%= link_to "취소", :back, class: "btn btn-warning" %>
        <%= link_to "스케줄", regrams_path, class: "btn btn-danger" %>
        <%= link_to "회원정보", edit_member_path(@member), class: "btn btn-info" %>
      </div>
    <% end %>
  </div>
</div>

app/views/regrams/index.html.erb
<%= render partial: 'nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <div class="col-xs-12">
      <%= month_calendar do |date| %>
        <p class="day-title text-center"><%= date.day %></p>
        <% @timepool.all.each do |t| %>
          <p>
            <span><%= t.time %></span>
            <% if Regram.where(date: date, timepool_id: t.id).take.nil? %>
              <% if date >= Date.today %>
                <%= link_to "+", new_regram_path(date: date, time: t.time), class: "content text-center" %>
              <% end %>
            <% else %>
              <%= link_to Regram.where(date:date, timepool_id: t.id).take.member.email, edit_regram_path(Regram.where(date:date, timepool_id: t.id).take.id), class: "content text-center" %>
            <% end %>
          </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/regrams/new.html.erb
<%= render partial: 'nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <%= nested_form_for @regram, html: { class: "form-group form-regram", multipart: true } do |f| %>
      <%= render partial: 'form', locals: { f: f, regram: @regram, member: @member, date: @date, time: @time } %>
      <div class="btn-wrapper">
        <%= f.submit "저장", class: "btn btn-primary" %>
        <%= link_to "메뉴", @member.nil? ? regrams_path : edit_member_path(@member.id), class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>