config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'

  get 'products/raw' => 'products#raw'
  get 'products/all' => 'products#all'
  get 'products/list' => 'products#list'
  get 'products/pre_view' => 'products#pre_view'
  get 'products/:id/pre_view' => 'products#pre_view'
  get 'tag/:id/destroy' => 'tags#destroy', as: :tag_destroy

  post 'products/imagecrop' => 'products#imagecrop'
  post 'regrams/tag' => 'regrams#tag'
  post 'rocket_regrams/tag' => 'rocket_regrams#tag'

  resources :homes
  resources :products, shallow: true do
    member do
      get 'empty'
    end
  end
  resources :members
  resources :regrams
  resources :tags
  resources :counts
  resources :rockets, shallow: true do
    resources :mission_checks do
      collection do
        post 'change'
      end
    end
    resources :missions
    resources :rocket_regrams do
      collection do
        get 'list'
      end
    end
    member do
      get 'calendar'
      get 'attend'
      get 'attend_show'
      get 'absent'
      get 'mission'
      post 'check'
      post 'upload_csv'
      post 'reset_apply'
    end
  end
  resources :rocket_members
  resources :rocket_apply do
    member do
      get 'excel'
      post 'pass'
    end
  end
  resources :facebooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rocket.rb
class Rocket < ApplicationRecord
  has_many :rocket_members, dependent: :destroy

  has_many :rocket_regrams, dependent: :destroy

  has_many :missions, dependent: :destroy
end

app/controllers/rockets_controller.rb
class RocketsController < ApplicationController
  require 'capybara'
  require 'capybara/dsl'
  require 'capybara/poltergeist'

  include Capybara::DSL

  def index
    @rockets = Rocket.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @rocketss }
    end
  end

  def new
    @rocket = Rocket.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @rocket }
    end
  end

  def create
    @rocket = Rocket.new(rocket_params)

    respond_to do |format|
      if @rocket.save
        flash[:notice] = 'Rocket was successfully created.'
        format.html { redirect_to rockets_path }
        format.xml  { render xml: @rocket, status: :created, location: @rocket }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @rocket.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @rocket = Rocket.find(params[:id])
    @start_date = @rocket.start_date.to_date

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @rocket }
    end
  end

  def calendar
    @rocket = Rocket.find(params[:id])
    @count = @rocket.rocket_members.pass.count

    respond_to do |format|
      format.html # calendar.html.erb
      format.xml { render xml: @rocket }
    end
  end

  def edit
    @rocket = Rocket.find(params[:id])
    @missions = @rocket.missions.all.reverse
    @count = @rocket.missions.count
  end

  def update
    @rocket = Rocket.find(params[:id])

    respond_to do |format|
      if @rocket.update(rocket_params)
        flash[:notice] = 'Rocket was successfully updated.'
        format.html { redirect_to rockets_path }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @rocket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @rocket = Rocket.find(params[:id])
    @rocket.destroy

    respond_to do |format|
      format.html { redirect_to(rockets_url) }
      format.xml  { head :ok }
    end
  end

  def attend
    @rocket = Rocket.find(params[:id])
    @date = params[:date].nil? ? (Date.today - 1) : params[:date]

    Capybara.default_driver = :poltergeist

    @img = []
    @url = []
    rocket_member_ids = []
    @rocket.rocket_members.pass.pluck(:group).uniq.sort.each do |g|
      rocket_member_ids += @rocket.rocket_members.pass.where(group: g).all.pluck(:id).sort
    end

    @member = RocketMember.find(rocket_member_ids).paginate(page: params[:page], per_page: 4)
    @member.pluck(:email).each_with_index do |m, index|
      visit "https://www.instagram.com/" + m + "/"
      sleep 1

      item = []
      href = []
      all(:css, 'img').each do |i|
        if item.count < 5
          item << i['src']
          #img = i['src'].split('/')
          #if img.count == 9
            #item << "#{img[0]}/#{img[1]}/#{img[2]}/#{img[3]}/#{img[6]}/#{img[8]}"
          #else
            #item << "#{img[0]}/#{img[1]}/#{img[2]}/#{img[3]}/#{img[6]}/#{img[7]}"
          #end
        end

        url = i.find(:xpath, '../../..')['href']
        href << url
      end
      item -= [item[0]]
      href -= [href[0]]

      @img << item
      @url << href
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @model_class_names }
    end
  end

  def attend_show
    @rocket = Rocket.find(params[:id])
    @date = params[:date].nil? ? (Date.today - 1) : params[:date].to_date

    Capybara.default_driver = :poltergeist

    @img = []
    @url = []
    @member = RocketMember.find(params[:member_id])
    visit "https://www.instagram.com/" + @member.email + "/"

    item = []
    href = []
    all(:css, 'img').each do |i|
      if item.count < 5
        item << i['src']
        #img = i['src'].split('/')
        #if img.count == 9
          #item << "#{img[0]}/#{img[1]}/#{img[2]}/#{img[3]}/#{img[6]}/#{img[8]}"
        #else
          #item << "#{img[0]}/#{img[1]}/#{img[2]}/#{img[3]}/#{img[6]}/#{img[7]}"
        #end
      end

      url = i.find(:xpath, '../../..')['href']
      href << url
    end
    item -= [item[0]]
    href -= [href[0]]

    @img = item
    @url = href

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @model_class_names }
    end

  end

  def absent
    @rocket = Rocket.find(params[:id])
    @date = params[:date].nil? ? (Date.today-1) : params[:date]

    Capybara.default_driver = :poltergeist

    @img = []
    @url = []
    ids = []
    @rocket.rocket_members.pass.all.each do |m|
      if m.attends.where(date: Date.today - 1).present?
        unless m.attends.where(date: Date.today - 1).take.status == "attendance"
          ids << m.id
        end
      else
        ids << m.id
      end
    end

    @member = RocketMember.where(id: ids).all.paginate(page: params[:page], per_page: 4)
    @member.pluck(:email).each_with_index do |m, index|
      visit "https://www.instagram.com/" + m + "/"
      sleep 1

      item = []
      href = []
      all(:css, 'img').each do |i|
        if item.count < 5
          item << i['src']
        end

        url = i.find(:xpath, '../../..')['href']
        href << url
      end
      item -= [item[0]]
      href -= [href[0]]

      @img << item
      @url << href
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @model_class_names }
    end
  end

  def check
    @date = Date.new params[:date1].to_i, params[:date2].to_i, params[:date3].to_i
    @rocket_member = RocketMember.find(params[:id])

    @rocket_member.attends.where(date: @date).destroy_all
    @attend = @rocket_member.attends.create(rocket_id: params[:rocket_id],
                                            status: params[:status].to_i,
                                            date: @date)

    render json: {id: params[:id], status: params[:status]}
  end

  def mission
    @rocket = Rocket.find(params[:id])
    @start_date = @rocket.start_date.to_date

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @rocket }
    end
  end

  def upload_csv
    @rocket = Rocket.find(params[:id])
    file = Roo::Spreadsheet.open(params[:file])
    count = file.sheet(0).column(1).drop(1).count
    #ids = file.sheet(0).column(5).drop(1)
    ids = file.sheet(0).column(3).drop(1)
    #identities = file.sheet(0).column(2).drop(1)
    identities = file.sheet(0).column(1).drop(1)
    #applications = file.sheet(0).column(4).drop(1)
    applications = file.sheet(0).column(2).drop(1)

    for i in 0..(count-1) do
      RocketMember.create(email: ids[i],
                          identity: identities[i],
                          application: applications[i],
                          group: 0,
                          rocket_id: @rocket.id)
    end

    respond_to do |format|
      format.html { redirect_to edit_rocket_path(@rocket.id) }
      format.xml  { render xml: @rocket }
    end
  end

  def reset_apply
    @rocket = Rocket.find(params[:id])
    @rocket.rocket_members.destroy_all

    respond_to do |format|
      format.html { redirect_to edit_rocket_path(@rocket.id) }
      format.xml  { render xml: @rocket }
    end
  end

  private

  def rocket_params
    params.require(:rocket).permit(:unit, :term, :start_date, :end_date, :volume, :mission)
  end
end

app/helpers/rockets_helper.rb
module RocketsHelper
end

app/views/rockets/_form.html.erb
<%= f.label :unit, "기수" %>
<%= f.number_field :unit, required: true, class: "form-control" %>
<%= f.label :term, "운영일자" %>
<%= f.select :term, options_for_select([["31 DAYS", 31]]), {}, class: "form-control" %>
<%= f.label :start_date, "시작일" %>
<%= f.date_field :start_date, required: true, class: "form-control" %>
<%= f.label :end_date, "종료일" %>
<%= f.date_field :end_date, required: true, disabled: true, class: "form-control" %>
<%= f.hidden_field :end_date %>
<%= f.label :volume, "모집인원" %>
<%= f.number_field :volume, required: true, class: "form-control" %>
<%= f.label :mission, "미션" %>
<%= f.number_field :mission, required: true, class: "form-control", min: 0 %>

app/views/rockets/_nav.html.erb
<%= link_to root_path, class: "main-title-wrapper" do %>
  <h2 class="main-title">motemote</h2>
<% end %>

<div class="nav">
  <% if params[:controller] == "rockets" && (params[:action] == "new" || params[:action] == "edit") %>
    <%= link_to "로켓단 일정 생성", new_rocket_path, class: "main-link active" %>
  <% else %>
    <%= link_to "로켓단 일정 생성", new_rocket_path, class: "main-link" %>
  <% end %>
  <%= link_to "로켓단 신청자 확인", rocket_apply_index_path, class: "main-link #{ params[:controller] == "rocket_apply" && "active" }" %>
  <%= link_to "로켓단 멤버 등록(수동)", new_rocket_member_path, class: "main-link #{ params[:controller] == "rocket_members" && (params[:action] == "new" || params[:action] == "edit") && "active" }" %>
  <% if params[:controller] == "rockets" && params[:action] == "index" %>
    <%= link_to "로켓단 리스트", rockets_path, class: "main-link active" %>
  <% else %>
    <%= link_to "로켓단 리스트", rockets_path, class: "main-link" %>
  <% end %>
  <% if (params[:controller] == "rockets" && (params[:action] == "show" || params[:action] == "calendar")) || params[:controller] == "attend" && (params[:action] == "index" || params[:action] == "show") %>
    <%= link_to "출석 관리", "", class: "main-link active" %>
  <% end %>
</div>

app/views/rockets/_nav_sub.html.erb
<% if params[:controller] != "rocket_apply" %>
  <div class="sub-nav">
    <%= link_to "일자별 관리", calendar_rocket_path(id), class: "main-link #{ params[:action] == "calendar" && "active" }" %>
    <%= link_to "ID별 관리", rocket_path(id), class: "main-link #{ params[:controller] == "rockets" && params[:action] == "show" && "active" }" %>
    <%= link_to "인스타 확인", attend_rocket_path(id: id), class: "main-link #{ params[:controller] == "rockets" && (params[:action] == "attend" || params[:action] == "attend_show") && "active" }" %>
    <%= link_to "미션 관리", rocket_missions_path(id), class: "main-link #{ params[:controller] == "missions" && params[:action] == "index" && "active" }" %>
    <%= link_to "미션 확인", new_rocket_mission_check_path(id), class: "main-link #{ params[:controller] == "missions" && params[:action] == "new" && "active" }" %>
    <%= link_to "불출석 확인", absent_rocket_path(id: id), class: "main-link #{ params[:controller] == "rockets" && params[:action] == "absent" && "active" }" %>
    <%= link_to "리그램 달력", rocket_rocket_regrams_path(rocket_id: id), class: "main-link #{ params[:controller] == "rocket_regrams" && (params[:action] == "index" || params[:action] == "new" || params[:action] == "edit") && "active" }" %>
    <%= link_to "리그램 리스트", list_rocket_rocket_regrams_path(rocket_id: id), class: "main-link #{ params[:controller] == "rocket_regrams" && params[:action] == "list" && "active" }" %>
    <%= select_tag :rocket_id, options_from_collection_for_select(Rocket.all, :id, :unit), class: "form-control sub-nav-rocket" %>
    <span class="btn btn-primary rocket-link">이동</span>
  </div>
<% else %>
  <div class="sub-nav">
    <%= link_to "엑셀 리스트", excel_rocket_apply_path(params[:id]), class: "main-link #{ params[:action] == "excel" && "active" }" %>
    <%= link_to "전체 리스트", rocket_apply_path(params[:id]), class: "main-link #{ params[:action] == "show" && "active" }" %>
    <%= link_to "보류 리스트", rocket_apply_path(params[:id], type: "hold"), class: "main-link #{ params[:action] == "show" && params[:type] == "hold" && "active" }" %>
    <%= link_to "최종 선정 리스트", rocket_apply_path(params[:id], type: "pass"), class: "main-link #{ params[:action] == "show" && params[:type] == "hold" && "active" }" %>
  </div>
<% end %>

app/views/rockets/_tr.html.erb
<tr class="center">
  <% if first %>
    <td class="rowspan" rowspan="<%= rocket.rocket_members.pass.where(group: g).count %>"><%= r.group %></td>
  <% end %>
  <td><%= rocket.rocket_members.pass.order(:group).pluck(:id).index(r.id) + 1 %></td>
  <td><%= link_to "#{r.email}", edit_rocket_member_path(r.id) %></td>
  <td><%= link_to "접속", "https://instagram.com/#{r.email}/", target: "_blank" %></td>
  <td><%= r.attends.where(status: "attendance").count + r.attends.where(status: "late").count * 0.5 %></td>
  <td><%= Attend.score(start_date, start_date + 10, r.id) %></td>
  <td><%= Attend.score(start_date + 10, start_date + 20, r.id) %></td>
  <td><%= Attend.score(start_date + 20, start_date + 30, r.id) %></td>
  <% for i in 0..(rocket.term - 1) do %>
    <td class="check">
      <%= link_to attend_show_rocket_path(r.rocket_id, member_id: r.id, date: rocket.start_date + i) do %>
        <% if Attend.status_of_attendance(rocket.start_date + i, r.id) == 0 %>
          &#927;
        <% elsif Attend.status_of_attendance(rocket.start_date + i, r.id) == 1 %>
          &#9653;
        <% else %>
          &#215;
        <% end %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/rockets/absent.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'rockets/nav_sub', locals: { id: @rocket.id } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <% @member.each_with_index do |m, index| %>
      <div class="attend-list">
        <div class="attend-list-left">
          <div class="attend-user-wrapper">
            <span class="attend-user-id"><%= m.email %></span>
            <%= link_to "접속", "https://www.instagram.com/#{m.email}/", target: "_blank", class: "attend-user-link" %>
          </div>
          <div class="attend-check-wrapper">
            <%= form_tag("", class: "flex attend-check-form") do %>
              <div class="attend-check-btn-wrapper">
                <%= date_select :attend, :date, order: [:year, :month, :day], default: Date.today-1 %>
                <div class="attend-btn-wrapper wrapper-<%= m.id %>">
                  <span id="<%= m.id %>-attend-0" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 0 && "status" %>">출석</span>
                  <span id="<%= m.id %>-attend-1" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 1 && "status" %>">지각</span>
                  <span id="<%= m.id %>-attend-2" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 2 && "status" %> last">불출석</span>
                </div>
                <%= hidden_field_tag :rocket_id, m.rocket_id %>
                <%= hidden_field_tag :status, "", require: true %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="attend-list-right">
          <% @img[index].each_with_index do |i, j| %>
            <%= link_to @url[index][j], target: :_blank do %>
              <%= image_tag i, class: "attend-image" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center" style="margin: 10px 0 30px 0;">
    <%= will_paginate @member %>
  </div>
</div>

app/views/rockets/attend.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'rockets/nav_sub', locals: { id: @rocket.id } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <% @member.each_with_index do |m, index| %>
      <div class="attend-list">
        <div class="attend-list-left">
          <div class="attend-user-wrapper">
            <span class="attend-user-id"><%= m.email %></span>
            <%= link_to "접속", "https://www.instagram.com/#{m.email}/", target: "_blank", class: "attend-user-link" %>
          </div>
          <div class="attend-check-wrapper">
            <%= form_tag("", class: "flex attend-check-form") do %>
              <div class="attend-check-btn-wrapper">
                <%= date_select :attend, :date, order: [:year, :month, :day], default: Date.today-1 %>
                <div class="attend-btn-wrapper wrapper-<%= m.id %>">
                  <span id="<%= m.id %>-attend-0" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 0 && "status" %>">출석</span>
                  <span id="<%= m.id %>-attend-1" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 1 && "status" %>">지각</span>
                  <span id="<%= m.id %>-attend-2" class="attend-btn <%= Attend.status_of_attendance(@date, m.id) == 2 && "status" %> last">불출석</span>
                </div>
                <%= hidden_field_tag :rocket_id, m.rocket_id %>
                <%= hidden_field_tag :status, "", require: true %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="attend-list-right">
          <% @img[index].each_with_index do |i, j| %>
            <%= link_to @url[index][j], target: :_blank do %>
              <%= image_tag i, class: "attend-image" %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="text-center" style="margin: 10px 0 30px 0;">
    <%= will_paginate @member %>
  </div>
</div>

app/views/rockets/attend_show.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'rockets/nav_sub', locals: { id: @rocket.id } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row">
    <div class="attend-list">
      <div class="attend-list-left">
        <div class="attend-user-wrapper">
          <span class="attend-user-id"><%= @member.email %></span>
          <%= link_to "접속", "https://www.instagram.com/#{@member.email}/", target: "_blank", class: "attend-user-link" %>
        </div>
        <div class="attend-check-wrapper">
          <%= form_tag("", class: "flex attend-check-form") do %>
            <div class="attend-check-btn-wrapper">
              <%= date_select("attend", "date", default: {year: @date.year, month: @date.month, day: @date.day}, order: [:year, :month, :day]) %>
              <div class="attend-btn-wrapper wrapper-<%= @member.id %>">
                <span id="<%= @member.id %>-attend-0" class="attend-btn <%= Attend.status_of_attendance(@date, @member.id) == 0 && "status" %>">출석</span>
                <span id="<%= @member.id %>-attend-1" class="attend-btn <%= Attend.status_of_attendance(@date, @member.id) == 1 && "status" %>">지각</span>
                <span id="<%= @member.id %>-attend-2" class="attend-btn <%= Attend.status_of_attendance(@date, @member.id) == 2 && "status" %> last">불출석</span>
              </div>
            </div>
            <%= hidden_field_tag :rocket_id, @member.rocket_id %>
            <%= hidden_field_tag :status, "", require: true %>
          <% end %>
        </div>
      </div>
      <div class="attend-list-right">
        <% @img.each_with_index do |i, j| %>
          <%= link_to @url[j], target: :_blank do %>
            <%= image_tag i, class: "attend-image" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rockets/calendar.html.erb
<%= render partial: 'nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { id: @rocket.id } %>

<div class="container fixed-sub">
  <div class="buffer"></div>
  <div class="row rocket-calendar">
    <%= month_calendar do |date| %>
      <p class="day-title text-center"><%= date.day %></p>
      <% if date >= @rocket.start_date && date <= @rocket.end_date %>
        <p class="center"><%= (date.to_date - @rocket.start_date.to_date + 1).to_i %>일차</p>
        <p class="center content">( <%= Attend.attend_members_count(date) %> / <%= @count %> )</p>
        <div class="content no-padding">
          <p class="center half left">출석</p>
          <p class="center half"><%= Attend.attend_members_count(date) %></p>
        </div>
        <div class="content no-padding">
          <p class="center half left">지각</p>
          <p class="center half"><%= Attend.lated_members_count(date) %></p>
        </div>
        <div class="content no-padding">
          <p class="center half left">결석</p>
          <p class="center half"><%= @count - Attend.attend_members_count(date) - Attend.lated_members_count(date) %></p>
        </div>
      <% else %>
        <p>&nbsp;</p>
        <p class="empty">&nbsp;</p>
        <p class="empty">&nbsp;</p>
        <p class="empty">&nbsp;</p>
        <p class="empty">&nbsp;</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rockets/edit.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed-sub">
  <div class="col-xs-12">
    <%= form_for @rocket, html: { class: "form-group form-member" } do |f| %>
      <p class="rocket-title">로켓단 정보 수정</p>
      <%= render partial: 'form', locals: { f: f } %>
      <div class="btn-wrapper">
        <%= f.submit "수정", class: "btn btn-primary" %>
        <%= link_to "취소", rockets_path, class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
  <div class="col-xs-12">
    <div class="rocket-wrapper">
      <p class="rocket-title">로켓단 지원자 등록</p>
      <% if @rocket.rocket_members.count == 0 %>
        <%= form_tag upload_csv_rocket_path(@rocket.id), method: 'post', multipart: true, class: 'rocket-apply-form' do %>
          <%= file_field_tag :file %>
          <%= submit_tag "파일등록", class: "btn btn-primary" %>
        <% end %>
      <% end %>
      <%= link_to "신청초기화", reset_apply_rocket_path, method: 'post', class: 'btn btn-danger' %>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="rocket-wrapper">
      <p class="rocket-title">로켓단 미션 등록</p>
      <table class="table table-hover table-mission">
        <thead>
          <th class="center">No</th>
          <th class="center">미션</th>
          <th class="center">날짜</th>
          <th class="center">삭제</th>
        </thead>
        <tbody>
          <% @missions.each_with_index do |m, index| %>
            <tr class="center" onclick="location.href='../../missions/<%= m.id %>/edit'">
              <td><%= index + 1 %></td>
              <td><%= m.content %></td>
              <td><%= m.date %></td>
              <td><%= link_to "삭제", mission_path(m.id), method: 'DELETE', class: "btn btn-default", style: "padding: 0 10px", data: {confirm: "삭제하시겠습니까?"} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="btn-wrapper">
        <% if @count < @rocket.mission %>
          <%= link_to "미션생성", new_rocket_mission_path(@rocket), class: "new-mission-btn btn btn-primary" %>
        <% else %>
          <p>미션을 최대로 생성하였습니다. ( 생성된 미션 수가 로켓단 미션 수와 같습니다. )</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rockets/index.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed-sub">
  <div class="col-md-12">
    <table class="table hover">
      <thead>
        <th class="center">No</th>
        <th class="center">일정목록</th>
        <th class="center">시작일</th>
        <th class="center">종료일</th>
        <th class="center">인원</th>
        <th class="center">수정</th>
        <th class="center">멤버</th>
        <th class="center">출석표</th>
        <th class="center">삭제</th>
      </thead>
      <tbody>
        <% @rockets.each_with_index do |r, index| %>
          <tr class="center">
            <td><%= index + 1 %></td>
            <td>로켓단 <%= r.unit %>기</td>
            <td><%= r.start_date.strftime("%y년 %m월 %d일") %></td>
            <td><%= r.end_date.strftime("%y년 %m월 %d일") %></td>
            <td><%= r.rocket_members.present? ? r.rocket_members.pass.size : 0 %> / <%= r.volume %></td>
            <td><%= link_to "수정", edit_rocket_path(r.id) %></td>
            <td><%= link_to "멤버", rocket_path(r.id) %></td>
            <td><%= link_to "출석표", calendar_rocket_path(r.id) %></td>
            <td><%= link_to "삭제", rocket_path(r.id), method: "DELETE", class: "btn btn-danger", data: { confirm: "관련 데이터 모두 삭제됩니다. 정말 삭제하시겠습니까?" } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/rockets/new.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed-sub">
  <div class="col-xs-12">
    <%= form_for @rocket, html: { class: "form-group form-member" } do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <div class="btn-wrapper">
        <%= f.submit "등록", class: "btn btn-primary" %>
        <%= link_to "취소", rockets_path, class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>