config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'

  get 'products/raw' => 'products#raw'
  get 'products/all' => 'products#all'
  get 'products/list' => 'products#list'
  get 'products/pre_view' => 'products#pre_view'
  get 'products/:id/pre_view' => 'products#pre_view'
  get 'tag/:id/destroy' => 'tags#destroy', as: :tag_destroy

  post 'products/imagecrop' => 'products#imagecrop'
  post 'regrams/tag' => 'regrams#tag'
  post 'rocket_regrams/tag' => 'rocket_regrams#tag'

  resources :homes
  resources :products, shallow: true do
    member do
      get 'empty'
    end
  end
  resources :members
  resources :regrams
  resources :tags
  resources :counts
  resources :rockets, shallow: true do
    resources :mission_checks do
      collection do
        post 'change'
      end
    end
    resources :missions
    resources :rocket_regrams do
      collection do
        get 'list'
      end
    end
    member do
      get 'calendar'
      get 'attend'
      get 'attend_show'
      get 'absent'
      get 'mission'
      post 'check'
      post 'upload_csv'
      post 'reset_apply'
    end
  end
  resources :rocket_members
  resources :rocket_apply do
    member do
      get 'excel'
      post 'pass'
    end
  end
  resources :facebooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/mission.rb
class Mission < ApplicationRecord
  has_many :mission_checks, dependent: :destroy
  has_many :missions, through: :mission_checks

  belongs_to :rocket
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @rocket = Rocket.find(params[:rocket_id])
    @missions = @rocket.missions.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @missions }
    end
  end

  def new
    @rocket = Rocket.find(params[:rocket_id])
    @mission = @rocket.missions.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @mission }
    end
  end

  def create
    @rocket = Rocket.find(params[:rocket_id])
    @mission = @rocket.missions.new(mission_params)

    respond_to do |format|
      if @mission.save
        flash[:notice] = 'Mission was successfully created.'
        format.html { redirect_to edit_rocket_path(@rocket) }
        format.xml  { render xml: @mission, status: :created, location: @mission }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @mission = Mission.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @mission }
    end
  end

  def edit
    @mission = Mission.find(params[:id])
    @rocket = @mission.rocket
  end

  def update
    @mission = Mission.find(params[:id])

    respond_to do |format|
      if @mission.update(mission_params)
        flash[:notice] = 'Mission was successfully updated.'
        format.html { redirect_to(@mission) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @mission = Mission.find(params[:id])
    @rocket = @mission.rocket
    @mission.destroy

    respond_to do |format|
      format.html { redirect_to edit_rocket_path(@rocket) }
      format.xml  { head :ok }
    end
  end

  private

  def mission_params
    params.require(:mission).permit(:content, :date, :rocket_id)
  end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<%= f.label :date, "미션날짜" %>
<%= f.date_field :date, required: true, class: "form-control" %>
<br />
<%= f.label :content, "미션내용" %>
<%= f.text_field :content, required: true, class: "form-control", style: "width: 955px; margin-bottom: 30px;" %>

app/views/missions/_nav_sub.html.erb
<div class="nav sub_nav">
  <% if params[:action] == "new" %>
    <%= link_to "미션생성", new_rocket_mission_path(rocket), class: "main-link active" %>
  <% end %>
  <% if params[:action] == "edit" %>
    <%= link_to "미션수정", edit_mission_path(mission), class: "main-link active" %>
  <% end %>
</div>

app/views/missions/_tr.html.erb
<tr class="center">
  <% if first %>
    <td class="rowspan" rowspan="<%= rocket.rocket_members.where(group: g).count %>" style="vertical-align: middle"><%= r.group %></td>
  <% end %>
  <td><%= rocket.rocket_members.pluck(:id).index(r.id) + 1 %></td>
  <td><%= link_to "#{r.email}", edit_rocket_member_path(r.id) %></td>
  <td><%= link_to "접속", "https://instagram.com/#{r.email}/", target: "_blank" %></td>
  <td><%= r.mission_checks.count %>
  <% rocket.missions.each do |m| %>
    <td>
      <%= link_to new_rocket_mission_check_path(mission_id: m.id, rocket_id: rocket.id, rocket_member_id: r.id) do %>
        <% if m.mission_checks.where(rocket_member_id: r.id).present? %>
          &#927;
        <% else %>
          &#215;
        <% end %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/missions/edit.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { mission: @mission } %>

<div class="row fixed-sub">
  <div class="col-xs-12">
    <%= form_for @mission, html: { class: "form-group form-member" } do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <div class="btn-wrapper">
        <%= f.submit "수정", class: "btn btn-primary" %>
        <%= link_to "취소", edit_rocket_path(@rocket), class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>

app/views/missions/index.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'rockets/nav_sub', locals: { id: @rocket.id } %>

<div class="row fixed-sub">
  <div class="col-md-12">
    <table class="table table-hover table-mission-index">
      <thead>
        <th class="center">Group</th>
        <th class="center">No</th>
        <th class="center">ID</th>
        <th class="center">접속</th>
        <th class="center">미션점수</th>
        <% @rocket.missions.each_with_index do |m, index| %>
          <th class="center"><%= m.date.strftime("%m/%d") %><br /><%= index + 1 %>회차</th>
        <% end %>
      </thead>
      <tbody>
        <% @rocket.rocket_members.pass.pluck(:group).uniq.sort.each do |g| %>
          <% @rocket.rocket_members.pass.where(group: g).first(1).each_with_index do |r, index| %>
            <%= render partial: 'tr', locals: { g: g, r: r, index: index, rocket: @rocket, first: true } %>
          <% end %>
          <% @rocket.rocket_members.pass.where(group: g).drop(1).each_with_index do |r, index| %>
            <%= render partial: 'tr', locals: { g: g, r: r, index: index, rocket: @rocket, first: false } %>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/missions/new.html.erb
<%= render partial: 'rockets/nav', locals: { } %>
<%= render partial: 'nav_sub', locals: { rocket: @rocket } %>

<div class="row fixed-sub">
  <div class="col-xs-12">
    <%= form_for @mission, url: rocket_missions_path, html: { class: "form-group form-member" } do |f| %>
      <%= render partial: 'form', locals: { f: f } %>
      <div class="btn-wrapper">
        <%= f.submit "생성", class: "btn btn-primary" %>
        <%= link_to "취소", edit_rocket_path(@rocket), class: "btn btn-warning" %>
      </div>
    <% end %>
  </div>
</div>