config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#index'

  get 'products/raw' => 'products#raw'
  get 'products/all' => 'products#all'
  get 'products/list' => 'products#list'
  get 'products/pre_view' => 'products#pre_view'
  get 'products/:id/pre_view' => 'products#pre_view'
  get 'tag/:id/destroy' => 'tags#destroy', as: :tag_destroy

  post 'products/imagecrop' => 'products#imagecrop'
  post 'regrams/tag' => 'regrams#tag'
  post 'rocket_regrams/tag' => 'rocket_regrams#tag'

  resources :homes
  resources :products, shallow: true do
    member do
      get 'empty'
    end
  end
  resources :members
  resources :regrams
  resources :tags
  resources :counts
  resources :rockets, shallow: true do
    resources :mission_checks do
      collection do
        post 'change'
      end
    end
    resources :missions
    resources :rocket_regrams do
      collection do
        get 'list'
      end
    end
    member do
      get 'calendar'
      get 'attend'
      get 'attend_show'
      get 'absent'
      get 'mission'
      post 'check'
      post 'upload_csv'
      post 'reset_apply'
    end
  end
  resources :rocket_members
  resources :rocket_apply do
    member do
      get 'excel'
      post 'pass'
    end
  end
  resources :facebooks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  require 'mechanize'
  require 'json'
  require 'date'

  has_many :counts, dependent: :destroy

  mount_uploader :image, ProductUploader

  def self.whenever_create
    mechanize = Mechanize.new
    login = mechanize.get('https://wms.nosnos.kr/wms/user/login')

    #look for the wanted form
    form = login.form_with(action: "https://wms.nosnos.kr/wms/user/login_chk")
    form.field_with(name: "company_code").value = ENV['SCM_COMPANY_CODE']
    form.field_with(name: "id").value = ENV['SCM_ID']
    form.field_with(name: "password").value = ENV['SCM_PASSWORD']
    form.submit

    scm = mechanize.get("https://wms.nosnos.kr/wms/inventory/stock/basic_list?page_per_list=100&search_mode=Y&member_ids%5B%5D=3&category_id=&upc=&product_name=&product_code=&product_codes=&stock_search_type=all&stock_start_cnt=&stock_end_cnt=")

    @data = {}
    count = scm.parser.css("table.tb-comm tbody tr").count

    for i in 1..count do
      @data[scm.parser.css("table.tb-comm tbody tr[#{i}] td[2]").text.to_sym] = scm.parser.css("table.tb-comm tbody tr[#{i}] td[9]").text.tr(',','').to_i
    end

    Product.all.each do |p|
      count = @data[:"#{p.code}"]

      if count.nil?
        Count.create(count: 0, product_id: p.id, date: Date.today.in_time_zone("Seoul"), goods: false)
      else
        if Count.where(product_id: p.id).where(date: (Date.today.in_time_zone("Seoul") - 1).to_s).take.present?
          if count > Count.where(product_id: p.id).where(date: (Date.today.in_time_zone("Seoul") - 1).to_s).take.count
            Count.create(count: count.nil? ? 0 : count, product_id: p.id, date: Date.today.in_time_zone("Seoul"), goods: true)
          else
            Count.create(count: count.nil? ? 0 : count, product_id: p.id, date: Date.today.in_time_zone("Seoul"), goods: false)
          end
        else
          Count.create(count: count.nil? ? 0 : count, product_id: p.id, date: Date.today.in_time_zone("Seoul"), goods: false)
        end
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require "mini_magick"

  def index
    @products = Product.all.order(:name)

    @count = 0
    @products.each do |p|
      if p.counts.last.present?
        @count += p.counts.last.count
      end
    end

    @price = 0
    @products.each do |p|
      if p.counts.last.present?
        @price += p.counts.last.count * p.price
      end
    end

    # 7일간 판매 평균 계산

    @average = []

    for i in 0..2 do
      sum = []
      @products.each do |p|
        if p.counts.where(date: Date.today - (7*(i+1)) - 1).present?
          for j in (7*i+1)..(7*i+7) do
            date = p.counts.last.date

            # 초기값 세팅 : 0
            if sum[p.id].nil?
              sum[p.id] = 0
            end

            sum[p.id] = sum[p.id] + p.counts.where(date: (date.to_date - j + 1).to_s).take.buffer + p.counts.where(date: (date.to_date - j).to_s).take.count - p.counts.where(date: (date.to_date - j + 1).to_s).take.count
          end
        else
          # 신제품의 경우 무조건 0
          sum[p.id] = 0
        end
      end

      avg = []
      sum.each_with_index do |s, index|
        if s.nil?
          s = 0
        end
        avg[index] = s/7
      end

      @average[i] = avg
    end

    @sell = []
    @products.each do |p|
      if p.counts.where(date: Date.today - 7).present?
        if @average[0][p.id] != 0
          @sell[p.id] = p.counts.last.count/@average[0][p.id]
        else
          @sell[p.id] = "-"
        end
      else
        @sell[p.id] = "-"
      end
    end

    @total = [0, 0, 0]

    for i in 0..2 do
      @products.each do |p|
        @total[i] += @average[i][p.id] * p.price
      end
    end

    # 판매 비중 (일주일 기준)
    @ratio = []
    @products.each do |p|
      @ratio[p.id] = ((@average[0][p.id] * p.price)*100).to_f/@total[0]
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render xml: @products }
    end
  end

  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render xml: @product }
    end
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        flash[:notice] = 'Product was successfully created.'
        format.html { redirect_to products_path }
        format.xml  { render xml: @product, status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update(product_params)
        flash[:notice] = 'Product was successfully updated.'
        format.html { redirect_to products_list_path }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def raw
    @products = Product.all
    @count = Count.all
    @date = 31 # 31일 기준

    # 입력을 못했을 경우 빈칸
    @diff = Date.today - Count.last.date.to_date
  end

  def all
    @products = Product.all
    @count = Count.all
    @all = Date.today - ("2017-05-22").to_date + 1  # 총 날짜 수

    # 입력을 못했을 경우 빈칸
    @diff = Date.today - Count.last.date.to_date
  end

  def list
    @products = Product.all
  end

  # require 'imgkit'
  def pre_view
    # html = 'http://' + request.domain + ':3000/products/pre_view'
    # kit = IMGKit.new(html, :quality => 80) # 이미지의 화질 및 용량 결정(80%)
    # f = File.new(Rails.root.join('app','assets','images','preview.png'), 'wb')
    # img = kit.to_img(:png)
    # send_data(img.to_jpg, :type=>"image/jpeg", :disposition=>'inline')
    # f.write(img)
    # f.close
    # kit = IMGKit.new(File.new(Rails.root.join('app', 'views', 'products', 'pre_view.html.erb')), :quality => 50)    
    # file = kit.to_file('preview.png')
    render 'pre_view'
  end

  def empty
    @product = Product.find(params[:id])
    if @product.empty
      @product.update(empty: false)
    else
      @product.update(empty: true)
    end

    respond_to do |format|
      format.html { redirect_to products_path }
      format.xml  { render xml: @products }
    end
  end

  def imagecrop
    @file = params[:image_file]
    # image = MiniMagick::Image.open(@file)
    # image.crop "260x112!+0+0"
    # image.write 'image.jpg'
    # system("open image.jpg")
    @crop_width = params[:width]
    @crop_height = params[:height]
    redirect_to action: 'list'
  end


  private

  def product_params
    params.require(:product).permit(:name, :code, :kind, :price, :date, :filename, :image, :product_detail)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_detail.html.erb
<script> 
    function pre_view() 
    { 
        var newWindow; 
        newWindow = window.open('pre_view', 'introwin', 'width=450,height=315,resizable=yo,scrollbars=no'); 
    } 
</script> 

<table class="edit-count">
    <tbody>
        <tr>
            <td class="td-label">
                <%= f.label(:product_detail, "제품 상세")%>
            </td>
            <td class="td-label">
                <form name="form"> 
                    <%= f.text_area(:product_detail, required: false, size: "40x20")%>
                    <input type="button" name="view" value="미리보기" onclick=pre_view()> 
                </form> 
            </td>
        </tr>
    </tbody>
</table>

app/views/products/_form.html.erb
<table class="edit-count">
  <tbody>
    <tr>
      <td class="td-label">
        <%= f.label(:code, "제품코드") %>
      </td>
      <td>
        <%= f.text_field(:code, required: true) %><br />
      </td>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:name, "상품명") %>
      </td>
      <td>
        <%= f.text_field(:name, required: true) %><br />
      </td>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:kind, "종류") %>
      </td>
      <td>
        <%= f.select(:kind, options_for_select(["note", "planner", "accessory"]), {}, class: 'form-control', required: true) %>
      </td>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:price, "가격") %>
      </td>
      <td>
        <%= f.number_field(:price, required: true) %>
      </td>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:date, "출시일") %>
      </td>
      <td>
        <%= f.date_field(:date, required: true) %>
      </td>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:filename, "파일명") %>
      </td>
      <td>
        <%= f.text_field(:filename, required: true)%>
    </tr>
    <tr>
      <td class="td-label">
        <%= f.label(:image, "썸네일") %>
      </td>
      <td>
        <%= f.file_field(:image, required: true, accept: 'image/png, image/gif, image/jpeg')%>
    </tr>
  </tbody>
</table>

app/views/products/_nav.html.erb
<%= link_to root_path, class: "main-title-wrapper" do %>
  <h2 class="main-title">motemote</h2>
<% end %>

<div class="nav">
  <% if params[:action] == "index" %>
    <%= link_to "상품메인", products_path, class: "main-link left active" %>
  <% else %>
    <%= link_to "상품메인", products_path, class: "main-link left" %>
  <% end %>
  <% if params[:controller] == "counts" && params[:action] == "new" %>
    <%= link_to "재고등록", new_count_path, class: "main-link active" %>
  <% else %>
    <%= link_to "재고등록", new_count_path, class: "main-link" %>
  <% end %>
  <% if params[:action] == "raw" || params[:action] == "all" %>
    <%= link_to "재고수량", products_raw_path, class: "main-link active" %>
  <% else %>
    <%= link_to "재고수량", products_raw_path, class: "main-link" %>
  <% end %>
  <% if params[:controller] == "products" && params[:action] == "new" %>
    <%= link_to "상품등록", new_product_path, class: "main-link active" %>
  <% else %>
    <%= link_to "상품등록", new_product_path, class: "main-link" %>
  <% end %>
  <% if params[:action] == "list" %>
    <%= link_to "상품목록", products_list_path, class: "main-link active" %>
  <% else %>
    <%= link_to "상품목록", products_list_path, class: "main-link" %>
  <% end %>
</div>

<% if params[:action] == "raw" || params[:action] == "all" %>
  <div class="sub-nav">
    <% if params[:action] == "raw" %>
      <%= link_to "30 DAYS", products_raw_path, class: "main-link sub-left active" %>
    <% else %>
      <%= link_to "30 DAYS", products_raw_path, class: "main-link sub-left" %>
    <% end %>
    <% if params[:action] == "all" %>
      <%= link_to "All", products_all_path, class: "main-link active" %>
    <% else %>
      <%= link_to "All", products_all_path, class: "main-link" %>
    <% end %>
  </div>
<% end %>

app/views/products/all.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed">
  <div class="col-md-12">
    <table class="table hover">
      <thead>
        <th>품목</th>
        <% for i in 1..@all do %>
          <th style="text-align:center"><%= Date.today - i + 1 %></th>
        <% end %>
      </thead>
      <tbody>
        <% @products.each do |p| %>
          <tr>
            <td class="name"><%= p.name %></td>
            <% for i in 0..(@diff-1) do %>
              <td></td>
            <% end %>
            <% @count.where(product_id: p.id).all.order('id DESC').each do |c| %>
              <% if c.goods? %>
                <td class=<%= c.buffer != 0 ? "green" : "red" %> style="text-align:center">
              <% elsif c.buffer != 0 %>
                <td class="yellow" style="text-align:center">
              <% else %>
                <td style="text-align:center">
              <% end %>
                  <%= link_to edit_count_path(c.id) do %>
                    <%= c.count %>
                  <% end %>
                </td>
            <% end %>
            <% for i in 0..(p.date.to_date - Date.today + @all - 2) do %>
              <td style="text-align:center"><a href="">0</a></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/products/edit.html.erb
<div class="container fixed">
  <div class="row">
    <div class="col-md-8 col-offset-md-2">
      <h1>입고 수량 입력</h1>
      <%= form_for @product, class: "edit-count-form" do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <%= render partial: 'detail', locals: { f: f }%>
        <%= submit_tag("수정", class: "btn btn-primary button", style: "margin-left: 110px;") %>
        <%= link_to "뒤로", :back, class: "btn btn-warning button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed">
  <div class="col-md-12">
    <table class="table hover">
      <thead>
        <th class="center">품목</th>
        <th class="center">상품코드</th>
        <th class="center">상품명</th>
        <th class="center">지지지난 7일간 평균판매량</th>
        <th class="center">지지난 7일간 평균판매량</th>
        <th class="center">지난 7일간 평균판매량</th>
        <th class="center">재고</th>
        <th class="center">판매가능일 수</th>
        <th class="center">재고가치</th>
        <th class="center">매출의 비중</th>
      </thead>
      <tbody>
        <% @products.each_with_index do |p, index| %>
          <tr class="center">
            <td><%= index + 1 %></td>
            <td><%= p.code %></td>
            <td><%= p.name %></td>
            <td><%= @average[2][p.id] %></td>
            <td><%= @average[1][p.id] %></td>
            <td><%= @average[0][p.id] %></td>
            <td><%= p.counts.present? ? p.counts.last.count : 0 %></td>
            <% if p.empty %>
              <td class="yellow"><%= link_to @sell[p.id], empty_product_path(p.id) %></td>
            <% else %>
              <% if @sell[p.id].to_i <= 30 %>
                <td class="red"><%= link_to @sell[p.id], empty_product_path(p.id) %></td>
              <% else %>
                <td><%= @sell[p.id] %></td>
              <% end %>
            <% end %>
            <td><%= p.counts.present? ? number_with_delimiter(p.counts.last.count * p.price, delimiter: ",") : 0 %></td>
            <td><%= number_with_precision(@ratio[p.id], precision: 2) %>%</td>
          </tr>
        <% end %>
        <tr class="center">
          <td colspan="3" class="text-center">총합</td>
          <td><%= number_with_delimiter(@total[2], delimiter: ",") %></td>
          <td><%= number_with_delimiter(@total[1], delimiter: ",") %></td>
          <td><%= number_with_delimiter(@total[0], delimiter: ",") %></td>
          <td><%= number_with_delimiter(@count, delimiter: ",") %></td>
          <td></td>
          <td><%= number_with_delimiter(@price, delimiter: ",") %></td>
          <td>100%</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/products/list.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed" style="width:65%;">
  <div class="col-md-12">
    <table class="table hover">
      <thead>
        <th>품목</th>
        <th>상품코드</th>
        <th>썸네일</th>
        <th>상품명</th>
        <th>출시일</th>
        <th>수정</th>
      </thead>
      <tbody>
        <% @products.each_with_index do |p, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= p.code %></td>
            <td><%= image_tag("#{p.image.thumb}") %></td>
            <td><%= p.name %></td>
            <td><%= p.date %></td>
            <td><%= link_to "수정", edit_product_path(p) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<div style="width:30%; position:absolute; top:200px; right:10px; text-align:center; border:1px solid;">
  <h1>이미지 크롭</h1>
  <%= form_tag("/products/imagecrop", method: "post", name: "crop_info") do %>
    <%= csrf_meta_tag %>
    <p>파일 첨부</p>
    <input type="file" name="image_file" accept="image/*" style="width:200px; text-align:center;" required/>
    <p>가로 길이</p>
    <input type="number" name="width" style="width:200px; height:20px; text-align:center;" required/>
    <p>세로 경계값</p>
    <input type="text" name="height" style="width:200px; height:20px; text-align:center;" required/><br><br>
    <input type="submit" name="crop_button" value="변환하기" style="width:100px;">
  <% end %>
</div>

<!--
<table border="0" cellspacing="0" cellpadding="0" style="width:300;">
  <tr>
    <td colspan="2" align="left" bgcolor="#FFFFFF">
      <table border="0" cellpadding="0" cellspacing="0">
        <tr>
          <td height="25">
            <table id="addTable" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF" border="0">
              <tr>
                <td><input type="number" name="addText" style="width:300px; height:20px;"></td>
                <td align="left"></td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td colspan="5" bgcolor="#FFFFFF" height="25" align="center">
            <input name="addButton" type="button" style="cursor:hand" onClick="insRow()" value="추가">
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<table border="0" cellspacing="0" cellpadding="0" style="width:300px; text-align:center;">
  <tr>
    <td height="50">
    </td>
  </tr>
  <tr align="right">
    <td>
      <input type="button" name="button" value="변환하기" style="width:100px;" onClick="frmCheck();">
    </td>
  </tr>
</table>
</form>
</div>


<script type="text/javascript">
var oTbl;
//Row 추가
function insRow() {
  oTbl = document.getElementById("addTable");
  var oRow = oTbl.insertRow();
  oRow.onmouseover=function(){oTbl.clickedRowIndex=this.rowIndex}; //clickedRowIndex - 클릭한 Row의 위치를 확인;
  var oCell = oRow.insertCell();

  //삽입될 Form Tag
  var frmTag = "<input type=number name=addText style=width:300px; height:20px;> ";
  frmTag += "<input type=button value='삭제' onClick='removeRow()' style='cursor:hand'>";
  oCell.innerHTML = frmTag;
}
//Row 삭제
function removeRow() {
  oTbl.deleteRow(oTbl.clickedRowIndex);
}

function frmCheck(){
  var frm = document.form;
  
  for( var i = 0; i <= frm.elements.length - 1; i++ ){
    if( frm.elements[i].name == "addText" )
    {
      if( !frm.elements[i].value ){
        alert("텍스트박스에 값을 입력하세요!");
        frm.elements[i].focus();
	      return;
      }
    }
  }
}
</script>


<div class="row fixed" style="width:35%;">
  <div>이미지 크롭</div>
  <form action='' method='POST'>
    <input id="width" type="number" name="width" value="0">
    <input>
    <button>댓글 작성</button>
  </form>
</div> -->

app/views/products/new.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="container fixed">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <%= form_for @product, html: {class: "edit-count-form text-center"} do |f| %>
        <%= render partial: 'form', locals: { f: f } %>
        <%= render partial: 'detail', locals: { f: f} %>
        <%= submit_tag("등록", class: "btn btn-primary button") %>
        <%= link_to "뒤로", :back, class: "btn btn-warning button" %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/pre_view.html.erb
<script type="text/javascript">
    document.write(window.opener.document.getElementById('product_product_detail').value); 
</script>


<div id="status" style="text-align:right; position:fixed; top:10px; right:10px; z-index:10"></div>

<script>
    $(document).mousemove(function(e){
        var scroll_sum = parseInt(e.pageY) + parseInt($(document).scrollTop());
        $(window).scroll(function(){
            scroll_sum = parseInt(e.pageY) + parseInt($(document).scrollTop());
            $('#status').html(e.pageX+', '+scroll_sum);
        });
        if ($(document).scrollTop()>0){
            $('#status').html(e.pageX+', '+scroll_sum);
        }
        else {
            $('#status').html(e.pageX+', '+e.pageY);
        }
    })
</script>
<!-- >
<div id="status">
</div>
    $(document).ready(function(){

$(document).mousemove(function(e){
                $('#status').html(e.pageX +', '+ e.pageY);
            }); 
        })
        -->

app/views/products/raw.html.erb
<%= render partial: 'nav', locals: { } %>

<div class="row fixed">
  <div class="col-md-12">
    <table class="table hover">
      <thead>
        <th>ID</th>
        <th>품목</th>
        <% for i in 1..@date do %>
          <th style="text-align:center"><%= Date.today - i + 1 %></th>
        <% end %>
      </thead>
      <tbody>
        <% @products.each do |p| %>
          <tr>
            <td><%= p.id %></td>
            <td class="name"><%= p.name %></td>
            <% for i in 0..(@diff-1) do %>
              <td></td>
            <% end %>
            <% @count.where(product_id: p.id).where('date > ?', (Date.today-31)).order('id DESC').each do |c| %>
              <% if c.goods? %>
                <td class=<%= c.buffer != 0 ? "green" : "red" %> style="text-align:center">
              <% elsif c.buffer != 0 %>
                <td class="yellow" style="text-align:center">
              <% else %>
                <td style="text-align:center">
              <% end %>
                  <%= link_to edit_count_path(c.id) do %>
                    <%= c.count %>
                  <% end %>
                </td>
            <% end %>
            <% for i in 0..(p.date.to_date - Date.today + 30 - 1) do %>
              <td style="text-align:center"><a href="">0</a></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>